# Build script for game-embed.js
# Bundles sprites.js and game.js into a single embeddable file

$ErrorActionPreference = "Stop"
$GameDir = $PSScriptRoot
$SpritesFile = Join-Path $GameDir "sprites.js"
$GameFile = Join-Path $GameDir "game.js"
$TemplateFile = Join-Path $GameDir "game-embed-template.js"
$OutputFile = Join-Path $GameDir "game-embed.js"

Write-Host "Building game-embed.js..." -ForegroundColor Cyan

# Read source files
$spritesContent = Get-Content $SpritesFile -Raw
$gameContent = Get-Content $GameFile -Raw
$templateContent = Get-Content $TemplateFile -Raw

# Process game.js content to work in embedded context
$replacements = @(
    @("const canvas = document.getElementById('gameCanvas');", "const canvas = document.getElementById('motorcycle-runner-canvas');"),
    @("const gameOverlay = document.getElementById('gameOverlay');", "const gameOverlay = document.getElementById('motorcycle-game-overlay');"),
    @("const finalScoreEl = document.getElementById('finalScore');", "const finalScoreEl = document.getElementById('motorcycle-final-score');"),
    @("const dailyHighScoreEl = document.getElementById('dailyHighScore');", "const dailyHighScoreEl = document.getElementById('motorcycle-daily-high-score');"),
    @("const allTimeHighScoreEl = document.getElementById('allTimeHighScore');", "const allTimeHighScoreEl = document.getElementById('motorcycle-all-time-high-score');"),
    @("const restartBtn = document.getElementById('restartBtn');", "const restartBtn = document.getElementById('motorcycle-restart-btn');"),
    @("const orientationOverlay = document.getElementById('orientationOverlay');", "const orientationOverlay = document.getElementById('motorcycle-orientation-overlay');"),
    @("const instructionsEl = document.getElementById('instructions');", "const instructionsEl = document.getElementById('motorcycle-instructions');")
)

$processedGameContent = $gameContent
foreach ($replacement in $replacements) {
    $processedGameContent = $processedGameContent.Replace($replacement[0], $replacement[1])
}

$processedGameContent = $gameContent
foreach ($replacement in $replacements) {
    $processedGameContent = $processedGameContent.Replace($replacement[0], $replacement[1])
}

# Build the embed file (inject raw content - no escaping needed since we're using direct injection)
$embedContent = $templateContent `
    -replace '\$\{generateSpritesContent\(\)\}', $spritesContent `
    -replace '\$\{generateGameContent\(\)\}', $processedGameContent

# Add header comment
$header = @"
/**
 * game-embed.js - AUTO-GENERATED FILE
 * 
 * DO NOT EDIT THIS FILE DIRECTLY!
 * 
 * This file is automatically generated by build-embed.ps1
 * To make changes, edit the source files and rebuild:
 *   - game/sprites.js (sprite data)
 *   - game/game.js (game logic)
 *   - game/game-embed-template.js (wrapper/overlay)
 * 
 * Then run: cd game && .\build-embed.ps1
 */

"@

# Write unminified version first
$tempFile = Join-Path $GameDir "game-embed-temp.js"
Set-Content -Path $tempFile -Value ($header + $embedContent) -NoNewline

# Minify with esbuild
Write-Host "Minifying with esbuild..." -ForegroundColor Cyan
& esbuild $tempFile --minify --outfile=$OutputFile

# Clean up temp file
Remove-Item $tempFile

$sizeKB = [Math]::Round((Get-Item $OutputFile).Length / 1024)
Write-Host "Built game-embed.js ($sizeKB KB)" -ForegroundColor Green
Write-Host "Output: $OutputFile" -ForegroundColor Green
